name: DB Scripts Deployment workflow
run-name: DB Scripts Deployment Workflow - ${{ inputs.deploy_action }}
on:
  # push:
  #   branches: [master]
  workflow_dispatch:
    inputs:
      deploy_action:
        type: choice
        options:
          - deploy
          - rollback
        required: true
        description: Deploy or Rollback
        default: deploy

jobs:
  db-scripts-actions:
    runs-on: [ ubuntu-latest ]
    outputs:
      BUILD_NUMBER: ${{ steps.Init.outputs.BUILD_NUMBER }}
      
    steps:
    # Check out the repo
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Liquibase Validate
      uses: liquibase-github-actions/validate@v4.30.0
      with:
        changelogFile: "changelog.sql"
        url: ""
        contextFilter: ""
        defaultCatalogName: ""
        defaultSchemaName: ""
        driver: ""
        driverPropertiesFile: ""
        labelFilter: ""
        password: ""
        username: ""


    
