name: DB Scripts Deployment workflow
run-name: DB Scripts Deployment Workflow
on:
  push:
  # workflow_dispatch:
  #   inputs:
  #     deploy_action:
  #       type: choice
  #       - deploy
  #       - rollback
  #       required: true
  #       description: Deploy or Rollback
  #       default: deploy

jobs:
  db-scripts-actions:
    runs-on: [ ubuntu-latest ]
  env:
    env_value: DEV
      
  steps:
    # Check out the repo
    - name: Checkout
      uses: actions/checkout@v3

    - name: DotEnv action variables
      uses: xom9ikk/dotenv@v2.3.0
      with:
        path: ./variables
        mode: liquibase
    
    - name: setup dynamic variables 1
      run:  |
        OCP_URL=OCP_${{ env.env_value }}_URL
        echo "OCP URL is:" ${OCP_URL}
        echo "OCP_URL=${OCP_URL}" >> $GITHUB_ENV
    
    - name: Print Variable from above step
      run: |
        echo "{{ env.OCP_URL }}"
    